<?php
/**
 * @file
 * dennis_inline_placeholder.install
 */

/**
 * Implements hook_uninstall().
 */
function dennis_inline_placeholder_uninstall() {
	// Original module name
	// Delete variables.
	variable_del('dennis_dfp_inline_selector');
	variable_del('dennis_dfp_inline_placeholder');
	variable_del('dennis_dfp_inline_first_position');
	variable_del('dennis_dfp_inline_min_distance');
	// variable_del('dennis_dfp_inline_paragraph_length');
	variable_del('dennis_dfp_inline_max_number');
	variable_del('dennis_dfp_inline_paragraph');

	// New module name
	// Delete variables.
	variable_del('dennis_inline_placeholder_selector');
	variable_del('dennis_inline_placeholder_placeholder');
	variable_del('dennis_inline_placeholder_first_position');
	variable_del('dennis_inline_placeholder_min_distance');
	// variable_del('dennis_inline_placeholder_paragraph_length');
	variable_del('dennis_inline_placeholder_max_number');
	variable_del('dennis_inline_placeholder_paragraph');
}
